UMS.Presentation/Controllers/FacultyController.cs
using UMS.Services.Contracts;
using UMS.Service.ViewModels.Faculty;
using Microsoft.AspNetCore.Mvc;
using UMS.DataAccess.Entities.Models;
using UMS.Presentation.Utilities;

namespace UMS.Presentation.Controllers
{
    public class FacultyController : Controller
    {
        private readonly IServiceManager _service;
        public FacultyController(IServiceManager service)
        {
            _service = service;
        }
     
        [HttpGet]
        public async Task<IActionResult> Index(Guid universityId)
        {
            var models = await _service.FacultyService.GetFacultiesAsync(universityId, trackChanges: false);
            ViewBag.universityId = universityId;
            return View(models);
        }


        [HttpGet]
        public async Task<IActionResult> Details(Guid universityId, Guid id)
        {
            var model = await _service.FacultyService.GetFacultyAsync(universityId, id, trackChanges: false, new[] { NavigationProperties.Groups });
            ViewBag.universityId = universityId;
            return View(model);
        }

     
        [HttpGet]
        public ActionResult Create(Guid universityId)
        {
            ViewBag.universityId = universityId;
            return View();
        }

        
        [HttpPost]
        public async Task<ActionResult> Create(Guid universityId, FacultyForCreationViewModel FacultyForCreation)
        {
            if (ModelState.IsValid)
            {
                try
                {

                    await _service.FacultyService.CreateFacultyForUniversityAsync(universityId, FacultyForCreation, trackChanges: false);
                    return RedirectToAction(nameof(Index), new { universityId });
                }
                catch
                {
                    return View();
                }
            }
            return View();
        }


        [HttpGet]
        public async Task<IActionResult> Edit(Guid universityId, Guid id)
        {
            var model = await _service.FacultyService.GetFacultyAsync(universityId, id, trackChanges: false);
            ViewBag.universityId = universityId;
            var modelToUpdate = new FacultyForUpdateViewModel
            {
                Name = model.Name,
                Description = model.Description,
            };
            return View(modelToUpdate);
        }

        
        [HttpPost]
        public async Task<ActionResult> Edit(Guid universityId, Guid id, FacultyForUpdateViewModel FacultyForUpdate)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _service.FacultyService.UpdateFacultyForUniversityAsync(universityId, id, FacultyForUpdate, universityTrackChanges: false, facultyTrackChanges: true);
                    return RedirectToAction(nameof(Index), new { universityId });
                }
                return View();
            }
            catch (Exception ex)
            {
                ModelState.TryAddModelError(string.Empty, ex.Message);
                return View(ModelState);
            }
        }

       
        [HttpGet]
        public async Task<IActionResult> Delete(Guid universityId, Guid id)
        {
            var model = await _service.FacultyService.GetFacultyAsync(universityId, id, trackChanges: false);
            ViewBag.universityId = universityId;
            return View(model);
        }

   
        [HttpPost]
        public async Task<IActionResult> Delete(Guid universityId, Guid id, FacultyViewModel model)
        {
            try
            {
                await _service.FacultyService.DeleteFacultyForUniverstiyAsync(universityId, id, trackChanges: false);
                return RedirectToAction(nameof(Index), new { universityId });
            }
            catch
            {
                return View();
            }
        }
    }
}

UMS.Presentation/Controllers/GroupController.cs
using UMS.Services.Contracts;
using UMS.Service.ViewModels.Group;
using Microsoft.AspNetCore.Mvc;
using UMS.DataAccess.Entities.Models;
using UMS.Presentation.Utilities;

namespace UMS.Presentation.Controllers
{
    public class GroupController : Controller
    {
        private readonly IServiceManager _service;
        public GroupController(IServiceManager service)
        {
            _service = service;
        }
        
        [HttpGet]
        public async Task<IActionResult> Index(Guid facultyId)
        {
            var models = await _service.GroupService.GetGroupsAsync(facultyId, trackChanges: false);
            ViewBag.facultyId = facultyId;
            return View(models);
        }

      
        [HttpGet]
        public async Task<IActionResult> Details(Guid facultyId, Guid id)
        {
            var model = await _service.GroupService.GetGroupAsync(facultyId, id, trackChanges: false, new[] { NavigationProperties.Departments, NavigationProperties.Students });
            ViewBag.facultyId = facultyId;
            return View(model);
        }

      
        [HttpGet]
        public ActionResult Create(Guid facultyId)
        {
            ViewBag.facultyId = facultyId;
            return View();
        }

     
        [HttpPost]
        public async Task<ActionResult> Create(Guid facultyId, GroupForCreationViewModel GroupForCreation)
        {
            if (ModelState.IsValid)
            {
                try
                {

                    await _service.GroupService.CreateGroupForFacultyAsync(facultyId, GroupForCreation, trackChanges: false);
                    return RedirectToAction(nameof(Index), new { facultyId });
                }
                catch
                {
                    return View();
                }
            }
            return View();
        }


        [HttpGet]
        public async Task<IActionResult> Edit(Guid facultyId, Guid id)
        {
            var model = await _service.GroupService.GetGroupAsync(facultyId, id, trackChanges: false);
            ViewBag.facultyId = facultyId;
            var modelToUpdate = new GroupForUpdateViewModel
            {
                Name = model.Name,
                Scientific = model.Scientific,
            };
            return View(modelToUpdate);
        }


        [HttpPost]
        public async Task<ActionResult> Edit(Guid facultyId, Guid id, GroupForUpdateViewModel groupForUpdate)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _service.GroupService.UpdateGroupForFacultyAsync(facultyId, id, groupForUpdate, facultyTrackChanges: false, groupTrackChanges: true);
                    return RedirectToAction(nameof(Index), new { facultyId });
                }
                return View();
            }
            catch (Exception ex)
            {
                ModelState.TryAddModelError(string.Empty, ex.Message);
                return View(ModelState);
            }
        }


        [HttpGet]
        public async Task<IActionResult> Delete(Guid facultyId, Guid id)
        {
            var model = await _service.GroupService.GetGroupAsync(facultyId, id, trackChanges: false);
            ViewBag.facultyId = facultyId;
            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> Delete(Guid facultyId, Guid id, GroupViewModel model)
        {
            try
            {
                await _service.GroupService.DeleteGroupForFacultyAsync(facultyId, id, trackChanges: false);
                return RedirectToAction(nameof(Index), new { facultyId });
            }
            catch
            {
                return View();
            }
        }
    }
}

UMS.Presentation/Views/Faculty/Create.cshtml
@model UMS.Service.ViewModels.Faculty.FacultyForCreationViewModel

@{
    ViewData["Title"] = "Create";
    var universityId = ViewBag.universityId;
}

<div class="container">
    <h1 class="mt-4">Create Faculty</h1>

    <h4>FacultyForCreationViewModel</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" asp-route-universityId="@universityId" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-controller="Faculty" asp-action="Index" asp-route-universityId="@universityId" class="btn btn-secondary">Back to List</a>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

UMS.Presentation/Views/Faculty/Delete.cshtml
@model UMS.Service.ViewModels.Faculty.FacultyViewModel

@{
    ViewData["Title"] = "Delete";
    var universityId = ViewBag.universityId;
}

<div class="container">
    <h1 class="mt-4">Delete Faculty</h1>

    <h3>Are you sure you want to delete this?</h3>
   
        <div>
            <h4>FacultyViewModel</h4>
            <hr />
            <dl class="row">
                <dt class="col-sm-2">
                    Id
                </dt>
                <dd class="col-sm-10">
                    @Model.Id
                </dd>
                <dt class="col-sm-2">
                    Name
                </dt>
                <dd class="col-sm-10">
                    @Model.Name
                </dd>
                <dt class="col-sm-2">
                    Description
                </dt>
                <dd class="col-sm-10">
                    @Model.Description
                </dd>
            </dl>

        <form asp-action="Delete" method="post">
            <input type="submit" value="Delete" asp-controller="Faculty" asp-action="Delete" asp-route-universityId="@universityId" class="btn btn-danger" /> |
                <a asp-controller="Faculty" asp-action="Index" asp-route-universityId="@universityId" class="btn btn-secondary">Back to List</a>
        </form>
        </div>
</div>

UMS.Presentation/Views/Faculty/Details.cshtml
@model UMS.Service.ViewModels.Faculty.FacultyViewModel

@{
    ViewData["Title"] = "Details";
    var universityId = ViewBag.universityId;
}

<div class="container">
    <h1 class="mt-4">Faculty Details</h1>

    <div>
        <h4>Faculty Details</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                Id
            </dt>
            <dd class="col-sm-10">
                @Model.Id
            </dd>
            <dt class="col-sm-2">
                Name
            </dt>
            <dd class="col-sm-10">
                @Model.Name
            </dd>
            <dt class="col-sm-2">
                Description
            </dt>
            <dd class="col-sm-10">
                @Model.Description
            </dd>
        </dl>
    </div>

    <div>
        <a asp-controller="Faculty" asp-action="Edit" asp-route-id="@Model.Id" asp-route-universityId="@universityId" class="btn btn-warning">Edit</a> |
        <a asp-controller="Faculty" asp-action="Index" asp-route-universityId="@universityId" class="btn btn-secondary">Back to List</a>
    </div>
</div>

<div class="container">
    @if (Model.Groups is not null)
    {
        <h1 class="mt-4">Groups In @Model.Name Faculty</h1>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>
                        Id
                    </th>
                    <th>
                        Name
                    </th>
                    <th>
                        Scientific
                    </th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Groups)
                {
                    <tr>
                        <td>
                            @item.Id
                        </td>
                        <td>
                            @item.Name
                        </td>
                        <td>
                            @item.Scientific
                        </td>
                        <td>
                            <div class="btn-group">
                                <a asp-controller="Group" asp-action="Edit" asp-route-id="@item.Id" , asp-route-facultyId="@Model.Id" class="btn btn-warning">Edit</a>
                                <a asp-controller="Group" asp-action="Details" asp-route-id="@item.Id" asp-route-facultyId="@Model.Id" class="btn btn-info">Details</a>
                                <a asp-controller="Group" asp-action="Delete" asp-route-id="@item.Id" asp-route-facultyId="@Model.Id" class="btn btn-danger">Delete</a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <h1 class="mt-4">@Model.Name Faculty doesn't contain any Groups</h1>
    }
    <p>
        <a asp-controller="Group" asp-action="Create" asp-route-facultyId="@Model.Id" class="btn btn-primary">Create New</a>
    </p>
</div>

UMS.Presentation/Views/Faculty/Edit.cshtml
@model UMS.Service.ViewModels.Faculty.FacultyForUpdateViewModel

@{
    ViewData["Title"] = "Edit";
    var universityId = ViewBag.universityId;
}

<div class="container">
    <h1 class="mt-4">Edit Faculty</h1>

    <h4>FacultyForUpdateViewModel</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" asp-route-universityId="@universityId" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-controller="Faculty" asp-action="Index" asp-route-universityId="@universityId" class="btn btn-secondary">Back to List</a>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

UMS.Presentation/Views/Faculty/Index.cshtml
@model IEnumerable<UMS.Service.ViewModels.Faculty.FacultyViewModel>

@{
    ViewData["Title"] = "Index";
    var universityId = ViewBag.universityId;
}

<div class="container">
    <h1 class="mt-4">Faculty Index</h1>

    <p>
        <a asp-controller="Faculty" asp-action="Create" asp-route-universityId="@universityId" class="btn btn-primary">Create New</a>
    </p>

    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>
                    Id
                </th>
                <th>
                    Name
                </th>
                <th>
                    Description
                </th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.Id
                    </td>
                    <td>
                        @item.Name
                    </td>
                    <td>
                        @item.Description
                    </td>
                    <td>
                        <div class="btn-group">
                            <a asp-controller="Faculty" asp-action="Edit" asp-route-id="@item.Id" asp-route-universityId="@universityId" class="btn btn-warning">Edit</a>
                            <a asp-controller="Faculty" asp-action="Details" asp-route-id="@item.Id" asp-route-universityId="@universityId" class="btn btn-info">Details</a>
                            <a asp-controller="Faculty" asp-action="Delete" asp-route-id="@item.Id" asp-route-universityId="@universityId" class="btn btn-danger">Delete</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>