UMS.Presentation/Controllers/DepartmentController.cs
using UMS.Services.Contracts;
using UMS.Service.ViewModels.Department;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using UMS.Presentation.Utilities;

namespace UMS.Presentation.Controllers
{
    public class DepartmentController : Controller
    {
        private readonly IServiceManager _service;
        public DepartmentController(IServiceManager service)
        {
            _service = service;
        }

        [HttpGet]
        public async Task<IActionResult> Index(Guid groupId)
        {
            var models = await _service.DepartmentService.GetDepartmentsAsync(groupId, trackChanges: false);
            ViewBag.groupId = groupId;
            return View(models);
        }


        [HttpGet]
        public async Task<IActionResult> Details(Guid groupId, Guid id)
        {
            var model = await _service.DepartmentService.GetDepartmentAsync(groupId, id, trackChanges: false, new[] { NavigationProperties.DepartmentDivisions_Division });
            ViewBag.groupId = groupId;
            return View(model);
        }

        
        [HttpGet]
        public ActionResult Create(Guid groupId)
        {
            ViewBag.groupId = groupId;
            return View();
        }

        
        [HttpPost]
        public async Task<ActionResult> Create(Guid groupId, DepartmentForCreationViewModel departmentForCreation)
        {
            if (ModelState.IsValid)
            {
                try
                {

                    await _service.DepartmentService.CreateDepartmentForGroupAsync(groupId, departmentForCreation, trackChanges: false);
                    ViewBag.groupId = groupId;
                    return RedirectToAction(nameof(Index), new { groupId });
                }
                catch
                {
                    return View();
                }
            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid groupId, Guid id)
        {
            var model = await _service.DepartmentService.GetDepartmentAsync(groupId, id, trackChanges: false);
            ViewBag.groupId = groupId;
            var modelToUpdate = new DepartmentForUpdateViewModel
            {
                Name = model.Name,
            };
            return View(modelToUpdate);
        }


        [HttpPost]
        public async Task<ActionResult> Edit(Guid groupId, Guid id, DepartmentForUpdateViewModel departmentForUpdate)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _service.DepartmentService.UpdateDepartmentForGroupAsync(groupId, id, departmentForUpdate, groupTrackChanges: false, departmentTrackChanges: true);
                    return RedirectToAction(nameof(Index), new { groupId });
                }
                return View();
            }
            catch (Exception ex)
            {
                ModelState.TryAddModelError(string.Empty, ex.Message);
                return View(ModelState);
            }
        }


        [HttpGet]
        public async Task<IActionResult> Delete(Guid groupId, Guid id)
        {
            var model = await _service.DepartmentService.GetDepartmentAsync(groupId, id, trackChanges: false);
            ViewBag.groupId = groupId;
            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> Delete(Guid groupId, Guid id, DepartmentViewModel model)
        {
            try
            {
                await _service.DepartmentService.DeleteDepartmentForGroupAsync(groupId, id, trackChanges: false);
                return RedirectToAction(nameof(Index), new { groupId });
            }
            catch
            {
                return View();
            }
        }
    }
}

UMS.Presentation/Controllers/GroupController.cs
using UMS.Services.Contracts;
using UMS.Service.ViewModels.Group;
using Microsoft.AspNetCore.Mvc;
using UMS.DataAccess.Entities.Models;
using UMS.Presentation.Utilities;

namespace UMS.Presentation.Controllers
{
    public class GroupController : Controller
    {
        private readonly IServiceManager _service;
        public GroupController(IServiceManager service)
        {
            _service = service;
        }
        
        [HttpGet]
        public async Task<IActionResult> Index(Guid facultyId)
        {
            var models = await _service.GroupService.GetGroupsAsync(facultyId, trackChanges: false);
            ViewBag.facultyId = facultyId;
            return View(models);
        }

      
        [HttpGet]
        public async Task<IActionResult> Details(Guid facultyId, Guid id)
        {
            var model = await _service.GroupService.GetGroupAsync(facultyId, id, trackChanges: false, new[] { NavigationProperties.Departments, NavigationProperties.Students });
            ViewBag.facultyId = facultyId;
            return View(model);
        }

      
        [HttpGet]
        public ActionResult Create(Guid facultyId)
        {
            ViewBag.facultyId = facultyId;
            return View();
        }

     
        [HttpPost]
        public async Task<ActionResult> Create(Guid facultyId, GroupForCreationViewModel GroupForCreation)
        {
            if (ModelState.IsValid)
            {
                try
                {

                    await _service.GroupService.CreateGroupForFacultyAsync(facultyId, GroupForCreation, trackChanges: false);
                    return RedirectToAction(nameof(Index), new { facultyId });
                }
                catch
                {
                    return View();
                }
            }
            return View();
        }


        [HttpGet]
        public async Task<IActionResult> Edit(Guid facultyId, Guid id)
        {
            var model = await _service.GroupService.GetGroupAsync(facultyId, id, trackChanges: false);
            ViewBag.facultyId = facultyId;
            var modelToUpdate = new GroupForUpdateViewModel
            {
                Name = model.Name,
                Scientific = model.Scientific,
            };
            return View(modelToUpdate);
        }


        [HttpPost]
        public async Task<ActionResult> Edit(Guid facultyId, Guid id, GroupForUpdateViewModel groupForUpdate)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _service.GroupService.UpdateGroupForFacultyAsync(facultyId, id, groupForUpdate, facultyTrackChanges: false, groupTrackChanges: true);
                    return RedirectToAction(nameof(Index), new { facultyId });
                }
                return View();
            }
            catch (Exception ex)
            {
                ModelState.TryAddModelError(string.Empty, ex.Message);
                return View(ModelState);
            }
        }


        [HttpGet]
        public async Task<IActionResult> Delete(Guid facultyId, Guid id)
        {
            var model = await _service.GroupService.GetGroupAsync(facultyId, id, trackChanges: false);
            ViewBag.facultyId = facultyId;
            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> Delete(Guid facultyId, Guid id, GroupViewModel model)
        {
            try
            {
                await _service.GroupService.DeleteGroupForFacultyAsync(facultyId, id, trackChanges: false);
                return RedirectToAction(nameof(Index), new { facultyId });
            }
            catch
            {
                return View();
            }
        }
    }
}

UMS.Presentation/Views/Group/Create.cshtml
@model UMS.Service.ViewModels.Group.GroupForCreationViewModel

@{
    ViewData["Title"] = "Create";
    var facultyId = ViewBag.facultyId;
}

<div class="container">
    <h1 class="mt-4">Create Group</h1>

    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Scientific" class="control-label"></label>
                    <select asp-for="Scientific" class="form-control" asp-items="Html.GetEnumSelectList<ScientificType>()">
                        <option value="" disabled selected hidden>Please Select</option>
                    </select>
                    <span asp-validation-for="Scientific" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" asp-route-facultyId="@facultyId" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div class="mt-3">
        <a asp-controller="Group" asp-action="Index" asp-route-facultyId="@facultyId" class="btn btn-primary">Back to List</a>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

UMS.Presentation/Views/Group/Delete.cshtml
@model UMS.Service.ViewModels.Group.GroupViewModel

@{
    ViewData["Title"] = "Delete";
    var facultyId = ViewBag.facultyId;
}

<div class="container">
    <h1 class="mt-4">Delete Group</h1>

    <div>
        <h3>Are you sure you want to delete this?</h3>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                Id
            </dt>
            <dd class="col-sm-10">
                @Model.Id
            </dd>
            <dt class="col-sm-2">
                Name
            </dt>
            <dd class="col-sm-10">
                @Model.Name
            </dd>
            <dt class="col-sm-2">
                Scientific
            </dt>
            <dd class="col-sm-10">
                @Model.Scientific
            </dd>
        </dl>

        <form asp-action="Delete" class="mb-4">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            <a asp-controller="Group" asp-action="Index" asp-route-facultyId="@facultyId" class="btn btn-primary">Back to List</a>
        </form>
    </div>
</div>

UMS.Presentation/Views/Group/Details.cshtml
@model UMS.Service.ViewModels.Group.GroupViewModel

@{
    ViewData["Title"] = "Details";
    var facultyId = ViewBag.facultyId;
}

<div class="container">
    <h1 class="mt-4">Group Details</h1>

    <div>
        <h4>GroupViewModel</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                Id
            </dt>
            <dd class="col-sm-10">
                @Model.Id
            </dd>
            <dt class="col-sm-2">
                Name
            </dt>
            <dd class="col-sm-10">
                @Model.Name
            </dd>
            <dt class="col-sm-2">
                Scientific
            </dt>
            <dd class="col-sm-10">
                @Model.Scientific
            </dd>
        </dl>
    </div>

    <div class="mt-3">
        <a asp-controller="Group" asp-action="Edit" asp-route-facultyId="@facultyId" class="btn btn-warning">Edit</a> |
        <a asp-controller="Group" asp-action="Index" asp-route-facultyId="@facultyId" class="btn btn-primary">Back to List</a>
    </div>
    <div>
        @if (Model.Departments is not null)
        {
            <h1 class="mt-4">Departments In @Model.Name Group</h1>
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>
                            Id
                        </th>
                        <th>
                            Name
                        </th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Departments)
                    {
                        <tr>
                            <td>
                                @item.Id
                            </td>
                            <td>
                                @item.Name
                            </td>
                            <td>
                                <div class="btn-group">
                                    <a asp-controller="Department" asp-action="Edit" asp-route-id="@item.Id" , asp-route-groupId="@Model.Id" class="btn btn-warning">Edit</a>
                                    <a asp-controller="Department" asp-action="Details" asp-route-id="@item.Id" asp-route-groupId="@Model.Id" class="btn btn-info">Details</a>
                                    <a asp-controller="Department" asp-action="Delete" asp-route-id="@item.Id" asp-route-groupId="@Model.Id" class="btn btn-danger">Delete</a>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <h1 class="mt-4">@Model.Name Group doesn't contain any Departments</h1>
        }
        <p>
            <a asp-controller="Department" asp-action="Create" asp-route-groupId="@Model.Id" class="btn btn-primary">Create New</a>
        </p>
    </div>
</div>

UMS.Presentation/Views/Group/Edit.cshtml
@model UMS.Service.ViewModels.Group.GroupForUpdateViewModel

@{
    ViewData["Title"] = "Edit";
    var facultyId = ViewBag.facultyId;
}

<div class="container">
    <h1 class="mt-4">Edit Group</h1>

    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Scientific" class="control-label"></label>
                    <select asp-for="Scientific" class="form-control" asp-items="Html.GetEnumSelectList<ScientificType>()">
                        <option value="" disabled selected hidden>Please Select</option>
                    </select>
                    <span asp-validation-for="Scientific" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" asp-route-facultyId="@facultyId" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div class="mt-3">
        <a asp-controller="Group" asp-action="Index" asp-route-facultyId="@facultyId" class="btn btn-primary">Back to List</a>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

UMS.Presentation/Views/Group/Index.cshtml
@model IEnumerable<UMS.Service.ViewModels.Group.GroupViewModel>

@{
    ViewData["Title"] = "Index";
    var facultyId = ViewBag.facultyId;
}

<div class="container">
    <h1 class="mt-4">Group Index</h1>

    <p>
        <a asp-controller="Group" asp-action="Create" asp-route-facultyId="@facultyId" class="btn btn-primary">Create New</a>
    </p>

    <table class="table">
        <thead>
            <tr>
                <th>
                    Id
                </th>
                <th>
                    Name
                </th>
                <th>
                    Scientific
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.Id
                    </td>
                    <td>
                        @item.Name
                    </td>
                    <td>
                        @item.Scientific
                    </td>
                    <td>
                        <a asp-controller="Group" asp-action="Edit" asp-route-id="@item.Id" asp-route-facultyId="@facultyId" class="btn btn-warning">Edit</a> |
                        <a asp-controller="Group" asp-action="Details" asp-route-id="@item.Id" asp-route-facultyId="@facultyId" class="btn btn-info">Details</a> |
                        <a asp-controller="Group" asp-action="Delete" asp-route-id="@item.Id" asp-route-facultyId="@facultyId" class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>